import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

import type {
  CodexAdapter,
  CodexExecutionInput,
  CodexExecutionResult,
} from './codex-adapter.js'
import type {
  CreatePullRequestInput,
  CreatePullRequestResult,
  GhAdapter,
} from './gh-adapter.js'

export class FakeCodexAdapter implements CodexAdapter {
  readonly mode = 'fake' as const

  async exec(input: CodexExecutionInput): Promise<CodexExecutionResult> {
    const changePath = join(input.worktreePath, 'AI_PR_WORKER_FAKE_CHANGE.md')
    await mkdir(dirname(input.outputLastMessagePath), { recursive: true })
    await writeFile(
      changePath,
      [
        '# Fake AI PR Worker Change',
        '',
        'Generated by the built-in fake Codex adapter.',
        '',
        `Prompt digest: ${input.prompt.slice(0, 120)}`,
        '',
      ].join('\n'),
      'utf8',
    )
    await writeFile(
      input.outputLastMessagePath,
      'Fake codex run completed successfully.',
      'utf8',
    )

    return {
      stdout: 'fake codex exec ok',
      stderr: '',
      outputLastMessagePath: input.outputLastMessagePath,
      sessionId: 'fake-codex-session',
    }
  }
}

export class FakeGhAdapter implements GhAdapter {
  readonly mode = 'fake' as const

  async createPullRequest(
    input: CreatePullRequestInput,
  ): Promise<CreatePullRequestResult> {
    return {
      url: `https://example.invalid/pr/${encodeURIComponent(input.headBranch)}`,
      stdout: 'fake gh pr create ok',
      stderr: '',
    }
  }
}
