'use client'

import { Wrench } from 'lucide-react'

interface MockAdapterBadgeProps {
  mode: 'mock' | 'external'
  status: 'live' | 'fallback' | 'unavailable'
  className?: string
}

/**
 * Requirement 6.10: Clearly identifies when mock/fallback adapter is in use.
 * Never presents mock responses as if they were generated by a real AI.
 */
export function MockAdapterBadge({ mode, status, className }: MockAdapterBadgeProps) {
  if (mode === 'external' && status === 'live') {
    return null
  }

  const isMock = mode === 'mock'
  const isFallback = status === 'fallback'

  const label = isMock
    ? 'ローカル応答（AI非使用）'
    : isFallback
      ? 'フォールバック応答'
      : 'AI 未接続'

  const description = isMock
    ? 'この応答はAIではなくローカルロジックで生成されています。'
    : isFallback
      ? 'AI APIが利用できないため、代替ロジックの結果を表示しています。'
      : 'AI APIが設定されていません。'

  return (
    <div
      className={`inline-flex items-start gap-2 rounded-2xl border border-amber-200 bg-amber-50/80 px-3 py-2 dark:border-amber-900/40 dark:bg-amber-950/30 ${className ?? ''}`}
      role="status"
      aria-label={label}
    >
      <Wrench className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-600 dark:text-amber-300" />
      <div className="min-w-0">
        <p className="text-xs font-semibold text-amber-700 dark:text-amber-200">
          {label}
        </p>
        <p className="mt-0.5 text-[11px] leading-4 text-amber-600/80 dark:text-amber-300/70">
          {description}
        </p>
      </div>
    </div>
  )
}
