#!/usr/bin/env bash
# scripts/swarm/new-task.sh
#
# SwarmOps の TQ 起票ラッパー。vibe コーディングの入口。
#
# Usage:
#   bash scripts/swarm/new-task.sh TQ-104 "学習者が進捗シェアカードをSNSに出せる"
#
# 動作:
#   1. git switch -c tq/<id>
#   2. docs/swarmops/tasks/<id>/{vibe.md, spec.md} を雛形から生成
#   3. scripts/swarm/reset-db.sh --minimal を実行（軽量 seed）
#   4. 生成したファイルパスを表示（エディタは開かない）

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TEMPLATES_DIR="$ROOT_DIR/docs/swarmops/templates"
TASKS_DIR="$ROOT_DIR/docs/swarmops/tasks"

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <TQ-id> <one-line-vibe>" >&2
  exit 2
fi

TQ_ID="$1"
VIBE="$2"

if [[ ! "$TQ_ID" =~ ^TQ-[0-9]+$ ]]; then
  echo "TQ id must match TQ-<number>, got: $TQ_ID" >&2
  exit 2
fi

TASK_DIR="$TASKS_DIR/$TQ_ID"
# bash 3.2 (macOS 既定) 互換: ${VAR,,} は bash 4+ 専用のため tr で小文字化する
BRANCH="tq/$(echo "$TQ_ID" | tr '[:upper:]' '[:lower:]')"

cd "$ROOT_DIR"

echo "==> swarm:new-task ${TQ_ID}"

# 1. branch
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "   branch $BRANCH already exists — switching"
  git switch "$BRANCH"
else
  echo "   creating branch $BRANCH"
  git switch -c "$BRANCH"
fi

# 2. docs/swarmops/tasks/<id>/
mkdir -p "$TASK_DIR"
DATE_ISO="$(date -u +%Y-%m-%d)"

if [[ ! -f "$TASK_DIR/vibe.md" ]]; then
  sed -e "s|{{TQ_ID}}|$TQ_ID|g" \
      -e "s|{{VIBE}}|$VIBE|g" \
      -e "s|{{DATE}}|$DATE_ISO|g" \
      "$TEMPLATES_DIR/vibe.md" > "$TASK_DIR/vibe.md"
  echo "   wrote $TASK_DIR/vibe.md"
else
  echo "   vibe.md already exists — skipping"
fi

if [[ ! -f "$TASK_DIR/spec.md" ]]; then
  sed -e "s|{{TQ_ID}}|$TQ_ID|g" \
      -e "s|{{VIBE}}|$VIBE|g" \
      -e "s|{{DATE}}|$DATE_ISO|g" \
      "$TEMPLATES_DIR/spec.md" > "$TASK_DIR/spec.md"
  echo "   wrote $TASK_DIR/spec.md"
else
  echo "   spec.md already exists — skipping"
fi

# 3. reset DB (軽量 seed)
echo "==> resetting DB for clean TQ slate"
bash "$ROOT_DIR/scripts/swarm/reset-db.sh" --minimal

# 4. このブランチ（= worktree）専用の port を採番し .env.swarmops に記録
#    複数 worktree で `pnpm dev` が同じ :3200 を取りに行って衝突するのを防ぐ。
#    allocate-port.sh が "PORT=<n>" を返すのでそのまま env ファイルに書く。
ENV_FILE="$ROOT_DIR/.env.swarmops"
PORT_LINE="$(bash "$ROOT_DIR/scripts/swarm/allocate-port.sh")"
ALLOCATED_PORT="${PORT_LINE#PORT=}"
{
  echo "# auto-generated by scripts/swarm/new-task.sh"
  echo "# per-worktree port allocation (see scripts/swarm/allocate-port.sh)"
  echo "PORT=${ALLOCATED_PORT}"
  echo "PLAYWRIGHT_WEB_PORT=${ALLOCATED_PORT}"
} > "$ENV_FILE"
echo "   wrote $ENV_FILE (PORT=${ALLOCATED_PORT})"

# 5. 出力
cat <<EOF

==> ready:
   branch  : $BRANCH
   vibe    : $TASK_DIR/vibe.md
   spec    : $TASK_DIR/spec.md
   port    : ${ALLOCATED_PORT}  (persisted in .env.swarmops)

next:
   1. Claude: $TASK_DIR/vibe.md を肉付けし $TASK_DIR/spec.md に落とす
   2. Codex: docs/swarmops/codex-handoff.md の手順で spec.md を食わせて green まで回す
   3. 検証  : bash scripts/swarm/verify.sh
EOF
