import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import type { AtomRecord, PersonaAnchorRecord } from '@/lib/atoms/atom-repository'

// W65 (Wave 14): verify lesson_atom_capabilities backfill migration.
//
// Audit G4 root cause: lesson_atom_capabilities was empty so compile()
// reported every anchor required_capability as unsupported. The migration
// generated by scripts/backfill-atom-capabilities-db.mjs replays atom yaml
// capability_inputs / capability_outputs as idempotent INSERTs. This spec
// confirms (a) the migration shape is safe to replay, (b) row count is
// well above the 200-row MVP floor, and (c) once capabilityOutputs are
// populated on AtomRecord, buildAtomPlan stops reporting that capability
// as unsupported.

const MIGRATION_PATH = resolve(
  __dirname,
  '../../supabase/migrations/20260509180000_atom_capabilities_backfill.sql',
)

const migrationSql = readFileSync(MIGRATION_PATH, 'utf-8')

function countInserts(sql: string): number {
  const matches = sql.match(/INSERT INTO lesson_atom_capabilities/g)
  return matches ? matches.length : 0
}

describe('lesson_atom_capabilities backfill migration', () => {
  it('wraps the backfill in a single transaction', () => {
    expect(migrationSql).toContain('BEGIN;')
    expect(migrationSql).toContain('COMMIT;')
    const beginIndex = migrationSql.indexOf('BEGIN;')
    const commitIndex = migrationSql.lastIndexOf('COMMIT;')
    expect(beginIndex).toBeGreaterThanOrEqual(0)
    expect(commitIndex).toBeGreaterThan(beginIndex)
  })

  it('inserts at least 200 capability rows (MVP Done When threshold)', () => {
    const inserts = countInserts(migrationSql)
    expect(inserts).toBeGreaterThanOrEqual(200)
  })

  it('uses idempotent ON CONFLICT DO NOTHING on the primary key tuple', () => {
    // The migration must be safely replayable so it can land on top of
    // partial seeds (some atoms already have rows) without dup-key errors.
    expect(migrationSql).toContain(
      'ON CONFLICT (atom_id, capability, direction) DO NOTHING',
    )
    // Every INSERT line must include the conflict clause.
    const insertLines = migrationSql
      .split('\n')
      .filter((line) => line.startsWith('INSERT INTO lesson_atom_capabilities'))
    for (const line of insertLines) {
      expect(line).toContain('ON CONFLICT (atom_id, capability, direction) DO NOTHING')
    }
  })

  it('guards FK with WHERE EXISTS so missing lesson_atoms rows are skipped', () => {
    // FK target may not be present yet for atom.common.* (W63 lane). The
    // migration must not block on missing FK rows — `WHERE EXISTS` lets
    // those inserts no-op silently.
    const insertLines = migrationSql
      .split('\n')
      .filter((line) => line.startsWith('INSERT INTO lesson_atom_capabilities'))
    for (const line of insertLines) {
      expect(line).toMatch(/WHERE EXISTS \(SELECT 1 FROM lesson_atoms WHERE atom_id = '[^']+'\)/)
    }
  })

  it('only emits direction values input or output', () => {
    const insertLines = migrationSql
      .split('\n')
      .filter((line) => line.startsWith('INSERT INTO lesson_atom_capabilities'))
    for (const line of insertLines) {
      const match = line.match(/SELECT '[^']+', '[^']+', '([^']+)'/)
      expect(match).not.toBeNull()
      expect(['input', 'output']).toContain(match?.[1])
    }
  })
})

// --- Behavioral check: capabilityOutputs populated -> compile reports
// supported capabilities. This is the downstream effect that the backfill
// is meant to enable.

const {
  fetchAnchorForPersonaMock,
  fetchCurrentAtomsMock,
  fetchUserPersonaIdsMock,
} = vi.hoisted(() => ({
  fetchAnchorForPersonaMock: vi.fn(),
  fetchCurrentAtomsMock: vi.fn(),
  fetchUserPersonaIdsMock: vi.fn(),
}))

vi.mock('@/lib/atoms/atom-repository', () => ({
  fetchAnchorForPersona: fetchAnchorForPersonaMock,
  fetchCurrentAtoms: fetchCurrentAtomsMock,
  fetchUserPersonaIds: fetchUserPersonaIdsMock,
}))

import { buildAtomPlan } from '@/lib/planner/goal-first/plan-compiler'

function makeAtom(overrides: Partial<AtomRecord> & Pick<AtomRecord, 'atomId' | 'title'>): AtomRecord {
  return {
    atomId: overrides.atomId,
    versionId: overrides.versionId ?? `version-${overrides.atomId}`,
    status: overrides.status ?? 'reviewed',
    yamlContent: overrides.yamlContent ?? {},
    bodyMarkdown: overrides.bodyMarkdown ?? null,
    metadata: overrides.metadata ?? {},
    title: overrides.title,
    personaTags: overrides.personaTags ?? ['web-builder'],
    goalTags: overrides.goalTags ?? ['web-publish'],
    capabilityInputs: overrides.capabilityInputs ?? [],
    capabilityOutputs: overrides.capabilityOutputs ?? [],
    hardPrerequisites: overrides.hardPrerequisites ?? [],
    softPrerequisites: overrides.softPrerequisites ?? [],
    estimatedMinutes: overrides.estimatedMinutes ?? 15,
    deliverable: overrides.deliverable ?? { type: 'markdown_doc', validation: 'basic_manual_check_v1' },
    evidence: overrides.evidence ?? [],
    mediaSlots: overrides.mediaSlots ?? [],
  }
}

function makeAnchor(overrides: Partial<PersonaAnchorRecord> = {}): PersonaAnchorRecord {
  return {
    anchorId: overrides.anchorId ?? 'anchor.web-builder.default',
    personaId: overrides.personaId ?? 'persona.web-builder',
    orderedAtomIds: overrides.orderedAtomIds ?? [],
    requiredCapabilities: overrides.requiredCapabilities ?? [],
    description: overrides.description ?? 'default anchor',
  }
}

afterEach(() => {
  fetchAnchorForPersonaMock.mockReset()
  fetchCurrentAtomsMock.mockReset()
  fetchUserPersonaIdsMock.mockReset()
})

describe('buildAtomPlan with backfilled capability outputs', () => {
  it('drops anchor required capabilities from unsupported once capabilityOutputs cover them', async () => {
    // Two atoms with persona web-builder. atom-a's output covers the anchor
    // required capability `deploy-static-site`. With the backfill applied,
    // capabilityOutputs is no longer empty so the anchor cap is supported.
    const atomA = makeAtom({
      atomId: 'atom.web-builder.deploy-with-vercel-cli',
      title: 'Deploy with Vercel CLI',
      personaTags: ['web-builder'],
      goalTags: ['web-publish'],
      capabilityOutputs: ['deploy-static-site'],
    })
    const atomB = makeAtom({
      atomId: 'atom.web-builder.write-effective-prompts',
      title: 'Write effective prompts',
      personaTags: ['web-builder'],
      goalTags: ['web-publish'],
      capabilityInputs: ['basic-ai-requests'],
      capabilityOutputs: ['effective-prompting'],
    })

    fetchCurrentAtomsMock.mockResolvedValue([atomA, atomB])
    fetchAnchorForPersonaMock.mockResolvedValue(
      makeAnchor({
        orderedAtomIds: ['atom.web-builder.deploy-with-vercel-cli'],
        requiredCapabilities: ['deploy-static-site'],
      }),
    )

    const plan = await buildAtomPlan({
      goal: 'サイトを公開したい',
      goalTags: ['web-publish'],
      userPersonas: ['persona.web-builder'],
      completedAtomIds: [],
    })

    expect(plan.unsupportedCapabilities).not.toContain('deploy-static-site')
    expect(plan.coverageScore).toBeGreaterThan(0)
    expect(plan.steps.length).toBeGreaterThan(0)
  })

  it('keeps required capabilities flagged when no atom output covers them (regression guard)', async () => {
    // Inverse of the above — confirms the assertion above is meaningful and
    // not vacuously true. With capabilityOutputs empty, the anchor cap
    // remains in unsupportedCapabilities (this is the pre-W65 state).
    const atomA = makeAtom({
      atomId: 'atom.web-builder.deploy-with-vercel-cli',
      title: 'Deploy with Vercel CLI',
      personaTags: ['web-builder'],
      goalTags: ['web-publish'],
      capabilityOutputs: [],
    })

    fetchCurrentAtomsMock.mockResolvedValue([atomA])
    fetchAnchorForPersonaMock.mockResolvedValue(
      makeAnchor({
        orderedAtomIds: ['atom.web-builder.deploy-with-vercel-cli'],
        requiredCapabilities: ['deploy-static-site'],
      }),
    )

    const plan = await buildAtomPlan({
      goal: 'サイトを公開したい',
      goalTags: ['web-publish'],
      userPersonas: ['persona.web-builder'],
      completedAtomIds: [],
    })

    expect(plan.unsupportedCapabilities).toContain('deploy-static-site')
  })
})
